### ISSUE TITLE
Virt panic on very fast cpu changes

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#450]
```

06:52:34 main.go:410: engine: virt[mgmt4]: resource: EventRunDefaultImpl exited!
panic: close of closed channel
	panic: close of closed channel

goroutine 780 [running]:
github.com/purpleidea/mgmt/engine/graph.(*State).Init.func1(0xc400000020, 0x1a6e0f8)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/engine/graph/state.go:134 +0x57
github.com/purpleidea/mgmt/engine/resources.(*VirtRes).Watch(0xc4204a1d40, 0x0, 0x0)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/engine/resources/virt.go:330 +0x330
github.com/purpleidea/mgmt/engine/graph.(*Engine).Worker.func1(0xc420444780, 0x7f2c5e1ca6c0, 0xc4204a1d40, 0x1bd2ee0, 0xc4204a1d40)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/engine/graph/actions.go:307 +0xbd1
created by github.com/purpleidea/mgmt/engine/graph.(*Engine).Worker
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/engine/graph/actions.go:266 +0x4e4

real	1m55.215s

```

**Comment by purpleidea** [comment]
I believe this is fixed and was a result of us sharing the mainloop. Since we added the background API things have been stable! If something changes, please let me know!
