### ISSUE TITLE
printf crashes when used with string interpolation

### ISSUE THREAD

**Issue by amousset** [purpleidea/mgmt#478]
## Versions

* ```mgmt version 0.0.17-68-gd888748```
* Fedora 29

## Description:

When running:

```
import "fmt"

$test = "test"

print "print1" {
        msg => fmt.printf("${test} %s", $test),
}
```

mgmt crashes with:

```
./mgmt run --tmp-prefix lang --lang bug.mcl
2019-02-28 16:08:16.309748 I | cli: lang: lexing/parsing...
2019-02-28 16:08:16.312533 I | cli: lang: init...
2019-02-28 16:08:16.312566 I | cli: lang: interpolating...
2019-02-28 16:08:16.312613 I | cli: lang: building scope...
2019-02-28 16:08:16.312650 I | cli: lang: running type unification...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xbf5baa]

goroutine 1 [running]:
github.com/purpleidea/mgmt/lang/funcs/core/fmt.(*PrintfFunc).Polymorphisms(0xc000217080, 0xc0001f4550, 0xc00000dfe0, 0x2, 0x2, 0xc00000df01, 0x1, 0x2, 0x48, 0x48)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/funcs/core/fmt/printf_func.go:88 +0x13a
github.com/purpleidea/mgmt/lang.(*ExprCall).Unify(0xc0001f40f0, 0xc0003fb218, 0x20, 0x20, 0xc00000d2a0, 0x0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/structs.go:5092 +0xef7
github.com/purpleidea/mgmt/lang.(*StmtResField).Unify(0xc000329c50, 0xc00020e978, 0x5, 0x1, 0x2, 0xc00000d2a0, 0x1, 0x2)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/structs.go:905 +0x49
github.com/purpleidea/mgmt/lang.(*StmtRes).Unify(0xc00044fec0, 0xc0001f16e0, 0x1, 0x1, 0xc0001f16d0, 0x1)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/structs.go:277 +0x396
github.com/purpleidea/mgmt/lang.(*StmtProg).Unify(0xc00041d980, 0x7fc1c835d000, 0x0, 0x2, 0x2, 0xc0002203c0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/structs.go:2570 +0x2ae
github.com/purpleidea/mgmt/lang/unification.Unify(0x1dedd00, 0xc00041d980, 0xc0001f16a0, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/unification/unification.go:46 +0x52
github.com/purpleidea/mgmt/lang.(*GAPI).Cli(0xc00044eb40, 0xc0003298f0, 0x10, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lang/gapi.go:297 +0xa2f
github.com/purpleidea/mgmt/lib.run(0xc00025e840, 0x1af7aa5, 0x4, 0x1debcc0, 0xc00044eb40, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lib/run.go:78 +0x47b
github.com/purpleidea/mgmt/lib.CLI.func1(0xc00025e840, 0xc0002b0500, 0xc00025e840)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lib/cli.go:265 +0x53
github.com/urfave/cli.HandleAction(0x174c1e0, 0xc0000b9920, 0xc00025e840, 0x0, 0xc00041d560)
        /home/amousset/gopath/src/github.com/urfave/cli/app.go:502 +0xbe
github.com/urfave/cli.Command.Run(0x1af7aa5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003bc840, 0x1d, 0x0, ...)
        /home/amousset/gopath/src/github.com/urfave/cli/command.go:165 +0x459
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00013a1c0, 0xc00025e580, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/urfave/cli/app.go:383 +0x827
github.com/urfave/cli.Command.startApp(0x1af712a, 0x3, 0x0, 0x0, 0xc000397f90, 0x1, 0x1, 0x1af712a, 0x3, 0x0, ...)
        /home/amousset/gopath/src/github.com/urfave/cli/command.go:377 +0x808
github.com/urfave/cli.Command.Run(0x1af712a, 0x3, 0x0, 0x0, 0xc000397f90, 0x1, 0x1, 0x1af712a, 0x3, 0x0, ...)
        /home/amousset/gopath/src/github.com/urfave/cli/command.go:103 +0x80f
github.com/urfave/cli.(*App).Run(0xc00013a000, 0xc00003a1e0, 0x6, 0x6, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/urfave/cli/app.go:259 +0x6bb
github.com/purpleidea/mgmt/lib.CLI(0x1dbfd04, 0x4, 0x1dcc070, 0x12, 0x1000000, 0x0, 0x0)
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/lib/cli.go:391 +0x26b8
main.main()
        /home/amousset/gopath/src/github.com/purpleidea/mgmt/main.go:46 +0x61
```

**Comment by purpleidea** [comment]
Great find, and interesting discussion about this issue. I have a workaround fix, but holding out for the better solution!

**Comment by purpleidea** [comment]
This is now fixed in git master. If you find any more bugs please let us know :) Thanks again!

The fancier version of this is being tracked here: https://github.com/purpleidea/mgmt/issues/483
