### ISSUE TITLE
Panic race in upstream dbus via Mount resource

### ISSUE THREAD

**Issue by wdullaer** [purpleidea/mgmt#508]
## Versions:

* mgmt version (eg: `mgmt --version`): 0.0.18

* operating system/distribution (eg: `uname -a`): Ubuntu 29.04

## Description:

When running mgmt with the mount resource, it failed with a panic (sending on a closed channel).
When running the exact same mcl immediately after it succeeded; This feels like a race condition somewhere.

mcl file: https://paste.fedoraproject.org/paste/Yne3hT7EDeTPOn8WK5n2pA
log of the failed run: https://paste.fedoraproject.org/paste/dE5V0VkAkkW8c9DVypzNKw

**Comment by purpleidea** [comment]
mcl:

```
file "/mnt/disk1/" {
	state => "exists",
}

mount "/mnt/disk1" {
	state => "exists",
	device => "UUID=8f3b7486-7529-4552-820c-284232c8354d",
	type => "ext4",
	options => {
		"noatime"=>"",
		"defaults"=>"",
	},
}

file "/mnt/disk2/" {
	state => "exists",
}

mount "/mnt/disk2" {
	state => "exists",
	device => "UUID=ba85c14c-173a-4f71-8618-8733a46af67b",
	type => "ext4",
	options => {
		"noatime"=>"",
		"defaults"=>"",
	},
}

file "/mnt/disk3/" {
	state => "exists",
}

mount "/mnt/disk3" {
	state => "exists",
	device => "UUID=f01ded31-2132-495f-9900-45eda4980e60",
	type => "ext4",
	options => {
		"noatime"=>"",
		"defaults"=>"",
	},
}

file "/mnt/disk4/" {
	state => "exists",
}

mount "/mnt/disk4" {
	state => "exists",
	device => "UUID=ac0a0d55-8263-4e1b-8912-cc7942762141",
	type => "ext4",
	options => {
		"noatime"=>"",
		"defaults"=>"",
	},
}
```

log:

```
$ sudo mgmt run --converged-timeout 5 lang -l mounts.mcl
2019-04-22 17:52:46.612219 I | cli: lang: lexing/parsing...
2019-04-22 17:52:46.647114 I | cli: lang: init...
2019-04-22 17:52:46.647188 I | cli: lang: interpolating...
2019-04-22 17:52:46.647913 I | cli: lang: building scope...
2019-04-22 17:52:46.647996 I | cli: lang: running type unification...
2019-04-22 17:52:46.650889 I | cli: lang: input: mounts.mcl
2019-04-22 17:52:46.650958 I | cli: lang: tree:
.
├── metadata.yaml
└── mounts.mcl
17:52:46 hello.go:49: this is: mgmt, version: 0.0.18
17:52:46 hello.go:50: main: start: 1555948366651039131
17:52:46 main.go:192: main: working prefix is: /var/lib/mgmt/
17:52:46 pgp.go:69: PGP: Imported key: 12225DB4
17:52:46 main.go:192: main: etcd: seeds: no seeds specified!
17:52:46 etcd.go:446: Etcd: Bootstrapping...
17:52:46 etcd.go:361: Etcd: Connect: Endpoints: []
17:52:46 etcd.go:375: Etcd: Connect: CtxError...
17:52:46 etcd.go:655: Etcd: CtxError: Reason: CtxDelayErr(1s): No endpoints available yet!
17:52:46 etcd.go:1481: Etcd: Nominated: ubuntu-server=http://localhost:2380
17:52:46 etcd.go:1496: Etcd: StartServer(newCluster: true): ubuntu-server=http://localhost:2380
17:52:46 etcd.go:1771: Etcd: StartServer: Starting server...
17:52:47 etcd.go:361: Etcd: Connect: Endpoints: []
17:52:47 etcd.go:375: Etcd: Connect: CtxError...
17:52:47 etcd.go:655: Etcd: CtxError: Reason: CtxDelayErr(2s): No endpoints available yet!
17:52:47 etcd.go:1778: Etcd: StartServer: Done starting server!
17:52:47 etcd.go:1796: Etcd: StartServer: Server running...
17:52:47 etcd.go:1519: Etcd: Addresses are: http://localhost:2379
17:52:49 etcd.go:359: Etcd: Connect: Endpoints: ubuntu-server=http://localhost:2379
17:52:49 etcd.go:1843: Etcd: ApplyDeltaEvents: Event(PUT): ubuntu-server
17:52:49 etcd.go:1481: Etcd: Nominated: ubuntu-server=http://localhost:2380
17:52:49 etcd.go:466: Etcd: Startup: Volunteering...
17:52:49 etcd.go:1687: Etcd: Ideal cluster size is now: 5
17:52:49 etcd.go:1031: Etcd: Set(/_mgmt/idealClusterSize): &{cluster_id:14841639068965178418 member_id:10276657743932975437 revision:246 raft_term:34  <nil>}
17:52:49 etcd.go:1281: Etcd: Members: List: [ubuntu-server]
17:52:49 etcd.go:1304: Etcd: Leader: ubuntu-server
17:52:49 etcd.go:1323: Etcd: Volunteers: [ubuntu-server]
17:52:49 etcd.go:1327: Etcd: Quitters: []
17:52:49 etcd.go:1339: Etcd: Candidates: []
17:52:49 etcd.go:1281: Etcd: Members: List: [ubuntu-server]
17:52:49 etcd.go:1304: Etcd: Leader: ubuntu-server
17:52:49 etcd.go:1323: Etcd: Volunteers: [ubuntu-server]
17:52:49 etcd.go:1327: Etcd: Quitters: []
17:52:49 etcd.go:1339: Etcd: Candidates: []
17:52:50 main.go:192: main: waiting...
17:52:50 main.go:192: main: running...
17:52:50 main.go:192: main: waiting...
17:52:50 main.go:496: gapi: generating new graph...
17:52:50 main.go:496: gapi: swap!
17:52:50 main.go:496: gapi: lang: lexing/parsing...
17:52:50 main.go:496: gapi: lang: init...
17:52:50 main.go:496: gapi: lang: interpolating...
17:52:50 main.go:496: gapi: lang: building scope...
17:52:50 main.go:496: gapi: lang: running type unification...
17:52:50 main.go:496: gapi: lang: building function graph...
17:52:50 main.go:496: gapi: lang: function engine initializing...
17:52:50 main.go:496: gapi: lang: function engine validating...
17:52:50 main.go:496: gapi: lang: function engine starting...
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=8f3b7486-7529-4552-820c-284232c8354d)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=8f3b7486-7529-4552-820c-284232c8354d)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ba85c14c-173a-4f71-8618-8733a46af67b)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ba85c14c-173a-4f71-8618-8733a46af67b)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1/)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1/)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` changed
17:52:50 main.go:496: gapi: lang: stream...
17:52:50 main.go:496: gapi: lang: loop...
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ac0a0d55-8263-4e1b-8912-cc7942762141)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ac0a0d55-8263-4e1b-8912-cc7942762141)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3/)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3/)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ba85c14c-173a-4f71-8618-8733a46af67b)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1/)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=ac0a0d55-8263-4e1b-8912-cc7942762141)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4/)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3/)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=f01ded31-2132-495f-9900-45eda4980e60)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2/)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=8f3b7486-7529-4552-820c-284232c8354d)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str()` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4/)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk4/)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk1)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=f01ded31-2132-495f-9900-45eda4980e60)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(UUID=f01ded31-2132-495f-9900-45eda4980e60)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2/)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk2/)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(ext4)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(noatime)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` started
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(/mnt/disk3)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` started
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str()` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` started
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(defaults)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` started
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` changed
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `str(exists)` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` stopped
17:52:50 main.go:496: gapi: lang: funcs: func `map(str(noatime): str(), str(defaults): str())` stopped
17:52:50 main.go:496: gapi: generating new graph...
17:52:50 main.go:496: gapi: lang: running interpret...
17:52:50 main.go:414: engine: autoedge: adding autoedges...
17:52:50 main.go:414: engine: autogroup: algorithm: wrappedGrouper: NonReachabilityGrouper...
17:52:50 main.go:192: main: commit...
17:52:50 main.go:414: engine: graph sync...
17:52:50 main.go:192: main: graph: Vertices(8), Edges(0)
17:52:50 main.go:192: main: waiting...
17:52:50 main.go:414: engine: Worker(file[/mnt/disk2/])
17:52:50 main.go:414: engine: Watch(file[/mnt/disk2/])
17:52:50 main.go:414: engine: Worker(file[/mnt/disk1/])
17:52:50 main.go:414: engine: Worker(mount[/mnt/disk1])
17:52:50 main.go:414: engine: Watch(mount[/mnt/disk1])
17:52:50 main.go:414: engine: Watch(file[/mnt/disk1/])
17:52:50 main.go:414: engine: file[/mnt/disk1/]: CheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk1/]: resource: contentCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk1/]: resource: chmodCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk1/]: resource: chownCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk1/]: CheckApply(true): Return(true, <nil>)
17:52:50 main.go:414: engine: Worker(mount[/mnt/disk2])
17:52:50 main.go:414: engine: Watch(mount[/mnt/disk2])
17:52:50 main.go:414: engine: Worker(mount[/mnt/disk3])
17:52:50 main.go:414: engine: Watch(mount[/mnt/disk3])
17:52:50 main.go:414: engine: Worker(mount[/mnt/disk4])
17:52:50 main.go:414: engine: Watch(mount[/mnt/disk4])
17:52:50 main.go:414: engine: file[/mnt/disk2/]: CheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk2/]: resource: contentCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk2/]: resource: chmodCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk2/]: resource: chownCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk2/]: CheckApply(true): Return(true, <nil>)
17:52:50 main.go:414: engine: Worker(file[/mnt/disk3/])
17:52:50 main.go:414: engine: Worker(file[/mnt/disk4/])
17:52:50 main.go:414: engine: Watch(file[/mnt/disk4/])
17:52:50 main.go:414: engine: Watch(file[/mnt/disk3/])
17:52:50 main.go:414: engine: file[/mnt/disk4/]: CheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk4/]: resource: contentCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk4/]: resource: chmodCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk4/]: resource: chownCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk4/]: CheckApply(true): Return(true, <nil>)
17:52:50 main.go:414: engine: file[/mnt/disk3/]: CheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk3/]: resource: contentCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk3/]: resource: chmodCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk3/]: resource: chownCheckApply(true)
17:52:50 main.go:414: engine: file[/mnt/disk3/]: CheckApply(true): Return(true, <nil>)
17:52:50 main.go:414: engine: mount[/mnt/disk3]: CheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk3]: resource: fstabCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk4]: CheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk4]: resource: fstabCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk3]: resource: mountCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk1]: CheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk1]: resource: fstabCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk4]: resource: mountCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk1]: resource: mountCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk2]: CheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk2]: resource: fstabCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk2]: resource: mountCheckApply(true)
17:52:50 main.go:414: engine: mount[/mnt/disk1]: CheckApply(true): Return(false, <nil>)
panic: send on closed channel

goroutine 494 [running]:
github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal.func1(0xc4200b2678, 0xc420918640, 0xc4206c9ac0)
	/home/james/code/gopath/src/github.com/godbus/dbus/default_handler.go:267 +0xe7
created by github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal
	/home/james/code/gopath/src/github.com/godbus/dbus/default_handler.go:266 +0x21e
```

This might have been fixed by bc4bb1669c50cc42e7e8e89f4faade1e140f93c1 in godbus. My build might have used an earlier version of the lib. I will release a new build soon, and if you can ever reproduce, then I will dig into the upstream lib and check if there is a missing waitgroup. I am fairly confident the bug is not in our software directly.

**Comment by purpleidea** [comment]
This issue could also help mitigate this type of issue from bringing down all of mgmt too:

https://github.com/purpleidea/mgmt/issues/510

**Comment by purpleidea** [comment]
Forgot to mention it earlier sorry, but I think this might be now fixed in the 0.0.19 release (or git master). If you can reproduce, please let me know, if not I'll eventually close this. Thank you again for the report, it's very valuable information.

**Comment by wdullaer** [comment]
Good stuff :-)

Given that it's a race condition, it might be difficult to reproduce. When trying to reproduce the other issue with the mount provider, mgmt hosed my fstab file (I commented out some lines which I think confused the regex in the resource). Even though it's just a homelab server, I don't want to take it down for an extended period again at this moment.

**Comment by ffrank** [comment]
Running git master plus 42ecfc4. Following `mcl` works in general, but just ran into the described issue randomly.

```mcl
mount "/mnt/acceptance_mount" {
	state => "exists",
	device => "/tmp/loopdevice",
	type => "ext2",
	options => {
		"rw"=>"",
		"loop"=>"",
	},
}
```

mgmt output
```
demo@dev-app01-ffrank:~/go/src/github.com/purpleidea/mgmt$ sudo mgmt run --converged-timeout 10 --tmp-prefix lang mountest.mcl
2019-06-04 23:04:43.215286 I | cli: lang: lexing/parsing...
2019-06-04 23:04:43.230950 I | cli: lang: init...
2019-06-04 23:04:43.231038 I | cli: lang: interpolating...
2019-06-04 23:04:43.231210 I | cli: lang: building scope...
2019-06-04 23:04:43.231285 I | cli: lang: running type unification...
2019-06-04 23:04:43.231697 I | cli: lang: input: mountest.mcl
2019-06-04 23:04:43.231778 I | cli: lang: tree:
.
├── metadata.yaml
└── mountest.mcl
This is: mgmt, version: 0.0.19-30-ge15f110
Copyright (C) 2013-2019+ James Shubin and the project contributors
Written by James Shubin <james@shubin.ca> and the project contributors
23:04:43 main: start: 1559682283231920575
23:04:43 main: warning: working prefix directory is temporary!
23:04:43 main: working prefix is: /tmp/mgmt-dev-app01-ffrank-663211845
23:04:43 PGP: Created key: 6656357A
23:04:43 main: no seeds specified!
23:04:43 etcd: running...
23:04:43 etcd: watching chooser...
23:04:43 etcd: bootstrapping...
23:04:43 etcd: nominated: dev-app01-ffrank=http://localhost:2380
23:04:43 etcd: waiting for server...
23:04:43 etcd: server: runServer: (newCluster=true): dev-app01-ffrank=http://localhost:2380
23:04:43 etcd: server: starting...
23:04:44 etcd: server: ready
23:04:44 etcd: connect...
23:04:44 etcd: connected!
23:04:44 etcd: chooser: set dynamic cluster size to: 5
23:04:44 etcd: watching nominees...
23:04:44 etcd: nominated: dev-app01-ffrank=http://localhost:2380
23:04:44 etcd: watching volunteers...
23:04:44 etcd: volunteering...
23:04:44 etcd: watching endpoints...
23:04:44 main: etcd is ready!
23:04:44 main: waiting...
23:04:44 main: running...
23:04:44 main: waiting...
23:04:44 gapi: generating new graph...
23:04:44 gapi: swap!
23:04:44 gapi: lang: lexing/parsing...
23:04:44 etcd: volunteers: dev-app01-ffrank=http://localhost:2380
23:04:44 etcd: chooser: (dev-app01-ffrank=http://localhost:2380)/(dev-app01-ffrank=http://localhost:2380)
23:04:44 etcd: chooser result(+/-): []/[]
23:04:44 etcd: volunteers: dev-app01-ffrank=http://localhost:2380
23:04:44 etcd: chooser: (dev-app01-ffrank=http://localhost:2380)/(dev-app01-ffrank=http://localhost:2380)
23:04:44 etcd: chooser result(+/-): []/[]
23:04:44 gapi: lang: init...
23:04:44 gapi: lang: interpolating...
23:04:44 gapi: lang: building scope...
23:04:44 gapi: lang: running type unification...
23:04:44 gapi: lang: building function graph...
23:04:44 gapi: lang: function engine initializing...
23:04:44 gapi: lang: function engine validating...
23:04:44 gapi: lang: function engine starting...
23:04:44 gapi: lang: funcs: func `str("rw")` started
23:04:44 gapi: lang: funcs: func `str("rw")` changed
23:04:44 gapi: lang: funcs: func `str("loop")` started
23:04:44 gapi: lang: funcs: func `str("loop")` changed
23:04:44 gapi: lang: funcs: func `str("ext2")` started
23:04:44 gapi: lang: funcs: func `str("ext2")` changed
23:04:44 gapi: lang: funcs: func `str("/tmp/loopdevice")` started
23:04:44 gapi: lang: funcs: func `str("/tmp/loopdevice")` changed
23:04:44 gapi: lang: funcs: func `str("")` started
23:04:44 gapi: lang: funcs: func `str("")` changed
23:04:44 gapi: lang: funcs: func `str("exists")` started
23:04:44 gapi: lang: funcs: func `str("exists")` changed
23:04:44 gapi: lang: funcs: func `str("/mnt/acceptance_mount")` started
23:04:44 gapi: lang: funcs: func `str("/mnt/acceptance_mount")` changed
23:04:44 gapi: lang: funcs: func `str("")` started
23:04:44 gapi: lang: funcs: func `str("")` changed
23:04:44 gapi: lang: funcs: func `str("rw")` stopped
23:04:44 gapi: lang: funcs: func `str("loop")` stopped
23:04:44 gapi: lang: stream...
23:04:44 gapi: lang: loop...
23:04:44 gapi: lang: funcs: func `map(str("rw"): str(""), str("loop"): str(""))` started
23:04:44 gapi: lang: funcs: func `map(str("rw"): str(""), str("loop"): str(""))` changed
23:04:44 gapi: lang: funcs: func `str("")` stopped
23:04:44 gapi: lang: funcs: func `str("")` stopped
23:04:44 gapi: lang: funcs: func `str("/mnt/acceptance_mount")` stopped
23:04:44 gapi: lang: funcs: func `str("ext2")` stopped
23:04:44 gapi: lang: funcs: func `str("/tmp/loopdevice")` stopped
23:04:44 gapi: lang: funcs: func `str("exists")` stopped
23:04:44 gapi: generating new graph...
23:04:44 gapi: lang: funcs: func `map(str("rw"): str(""), str("loop"): str(""))` stopped
23:04:44 gapi: lang: running interpret...
23:04:44 engine: autoedge: adding autoedges...
23:04:44 engine: autogroup: algorithm: wrappedGrouper: NonReachabilityGrouper...
23:04:44 main: commit...
23:04:44 engine: graph sync...
23:04:44 main: graph: Vertices(1), Edges(0)
23:04:44 main: waiting...
23:04:44 main: converged for 10 seconds, exiting!
23:04:44 engine: Worker(mount[/mnt/acceptance_mount])
23:04:44 engine: Watch(mount[/mnt/acceptance_mount])
23:04:44 main: destroy...
23:04:44 main: deploy: exited
23:04:44 main: loop: exited
23:04:44 engine: graph sync...
23:04:44 engine: mount[/mnt/acceptance_mount]: CheckApply(true)
23:04:44 engine: mount[/mnt/acceptance_mount]: resource: mountCheckApply(true)
23:04:44 engine: mount[/mnt/acceptance_mount]: CheckApply(true): Return(false, <nil>)
panic: send on closed channel

goroutine 269 [running]:
github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal.func1(0xc00082a320, 0xc000245b80, 0xc0004df5c0)
	/home/demo/go/src/github.com/godbus/dbus/default_handler.go:267 +0xbb
created by github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal
	/home/demo/go/src/github.com/godbus/dbus/default_handler.go:266 +0x1c5
```

**Comment by purpleidea** [comment]
@ffrank 
I suspect your $GOPATH is out of date.
*First to confirm*, run `git log` in $GOPATH/src/github.com/godbus/dbus and paste here the top entry.

*Then* to fix it:
Try: `go get -u ./...`

*Then* run the above git log again. Make a new build.

You're most likely building against an old dep that fixed this issue. If it persists, let us know.

**Comment by purpleidea** [comment]
(As a result, I'm going to close for now. Comment if you think it's still present.)

**Comment by ffrank** [comment]
First top log
```
commit ade71ed3457e1a2d0edc32a59e718cc523e73b21
Author: Alexander Menzhinsky <amenzhinsky@gmail.com>
Date:   Thu Apr 18 14:35:00 2019 +0300

    Improve array memory allocations
```
No change through `go get -u ./...` (which I ran from mgmt's source dir; no effect when running it in dbus's).

**Comment by purpleidea** [comment]
Upstream pushed a new fix to fix this, so I will close again. If anyone experiences this again, please LMK. TBH, I think the dbus lib needs a good cleanup, but that's too big of a project for us to tackle for now.
